---
# We use the docker-compose services names for the _URI hostnames because
# localhost is not available within the test container:
# https://docs.docker.com/compose/networking/
# https://docs.docker.com/compose/environment-variables/#the-env-file
variables:
  API_URI: http://api:3000
  # Remove docker-compose warnings (because this environment variable is ised by
  # the test container):
  CONFIG_ONLY: "false"
  DB_URI: postgresql://test_db_user:test_db_password@localhost:5432/test_db
  ELASTIC_PASSWORD: test_elastic_password
  NODE_ENV: test
  PGRST_DB_ANON_ROLE: anonymous
  PGRST_DB_SCHEMA: api
  # It must be at least 32 characters long:
  # https://github.com/PostgREST/postgrest/issues/977#issuecomment-329917367
  PGRST_JWT_SECRET: a_test_only_postgrest_jwt_secret
  PGRST_PORT: 3000
  POSTGRES_DB: test_db
  POSTGRES_PASSWORD: test_db_password
  POSTGRES_PORT: 5432
  POSTGRES_USER: test_db_user
  TEST_WEB_URI: http://localhost:3100
  WEB_PORT: 3100

stages:
  - Test

E2E Tests:
  stage: Test
  image: igabriele/docker-compose-puppeteer
  # We both need to add the docker:dind service and the DOCKER_DRIVER +
  # DOCKER_HOST variables to use docker-in-docker:
  # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
  services:
    - docker:dind
    - igabriele/postgresql-jwt
    - ./packages/contrib
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
  before_script:
    - npm i -g wait-on
    - yarn --frozen-lockfile
    - yarn db:migrate
    - yarn db:seed
    - docker run -d postgrest/postgrest:v6.0.1-53b606e
    # - docker build -t web ./packages/contrib
    # - docker run -d web
    # Start db (we manually start it so that it has the time to start during the
    # other containers build process):
    # - docker-compose up -d db
    # Whis will build & start all the other containers as well as run database
    # migrations & seeds:
    # - CONFIG_ONLY=true docker-compose up -d --always-recreate-deps --build --force-recreate test
    # We need to restart the api container to apply the authentication process:
    # - docker-compose restart api
  script:
    - yarn test:e2e
  # We need to raise the container error to fail the CI run if the tests fail:
  # - docker-compose up --abort-on-container-exit --exit-code-from test test
  after_script:
    - docker-compose stop
