language: node_js
node_js:
  - "v12.16.0"

cache:
  yarn: true
  directories:
    - nodes_modules
    - packages/api/nodes_modules
    - packages/app/nodes_modules

jobs:
  include:
    - stage: Test
      name: Unit Tests
      install:
        - yarn --frozen-lockfile
      script:
        - yarn test
      after_script:
        # Push tests coverage data to Coveralls:
        - ./node_modules/.bin/coveralls < ./coverage/lcov.info
        # Push tests coverage data to Codecov:
        - npx codecov

    - stage: Test
      name: E2E Tests
      env:
        - NODE_ENV=production
      services:
        - docker
      before_script:
        # Copy default environment variables:
        - cp ./.env.example ./.env
        # Stop Travis out-of-the-box PostgreSQL services:
        - sudo service postgresql stop
        # Give execution rights to production script (used by "ci:test:e2e"):
        - sudo chmod +x ./scripts/prod/start.sh
        # Run production script:
        - ./scripts/prod/start.sh
      script:
        - yarn test:e2e

# Limit branches builds to "master" & "develop" ones:
branches:
  only:
    - develop
    - master

notifications:
  email:
    on_failure: change
    on_success: never
