language: node_js

node_js:
  - "10"

os:
  - linux

stages:
  - name: Test
  - name: Deployment
    if: tag =~ ^v\d+

jobs:
  include:
    - stage: Test
      name: Unit Tests
      before_script:
        - bash scripts/ci/install_docker_compose.sh
        - yarn setup
      script: yarn test

cache:
  yarn: true
  directories:
    - node_modules
