language: node_js

node_js:
  - "10"

os:
  - linux

stages:
  - name: Test
  - name: Deployment
    if: tag =~ ^v\d+

jobs:
  include:
    - stage: Test
      name: Unit Tests
      before_script: yarn run lerna bootstrap
      script: yarn test -- --stream -- --coverage
      after_success: npx codecov

    - stage: Test
      name: E2E Tests
      before_script:
        - bash scripts/ci/install_docker_compose.sh
        # We first need to stop the existing Postgre service to free 5432 port:
        - bash scripts/ci/stop_postgre_service.sh
        # Generate a .env file and migrate+seed Postgre database:
        - yarn setup
        # Start Docker Compose & a local server instance (in the background):
        - bash scripts/prod/start.sh
      script:
        - yarn test:e2e

cache:
  yarn: true
  directories:
    - node_modules
