language: node_js

node_js:
  - "10"

os:
  - linux

stages:
  - name: Test
  - name: Deployment
    if: tag =~ ^v\d+

jobs:
  include:
    - stage: Test
      name: Unit Tests
      before_script: yarn setup
      script: yarn test
