language: node_js
node_js:
  - "v12.18.0"

cache:
  yarn: true
  directories:
    - nodes_modules
    - packages/api/nodes_modules
    - packages/app/nodes_modules

jobs:
  include:
    - stage: Test
      name: Unit Tests
      install:
        - yarn --frozen-lockfile --ignore-scripts
      script:
        - yarn test
      after_success:
        - npx codecov

    - stage: Test
      name: E2E Tests
      env:
        - NODE_ENV=production
      services:
        - docker
      install:
        - yarn --frozen-lockfile --production=false --pure-lockfile
      before_script:
        # Copy default environment variables:
        - yarn setup:env
        # Stop Travis out-of-the-box PostgreSQL services:
        - sudo service postgresql stop
        # Run production script:
        - yarn start:prod
      script:
        - yarn test:e2e

# Limit branches builds to "master" & "develop" ones:
branches:
  only:
    - develop
    - master

notifications:
  email:
    on_failure: change
    on_success: never
