# This is the Docker file runnning E2E Tests.

FROM ubuntu:18.04

RUN apt-get update \
    && apt-get install -y \
    # Required below for nodejs installation
    curl \
    # https://stackoverflow.com/a/25908200/2736233
    sudo \
    # https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix
    gconf-service \
    libasound2 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgcc1 \
    libgconf-2-4 \
    libgdk-pixbuf2.0-0 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    ca-certificates \
    fonts-liberation \
    libappindicator1 \
    libnss3 \
    lsb-release \
    xdg-utils \
    wget

# https://stackoverflow.com/a/25908200/2736233
RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo

# https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#recommended-enable-user-namespace-cloning
# RUN sudo sysctl -w kernel.unprivileged_userns_clone=1

RUN sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - \
    && apt-get update \
    && apt-get install -y nodejs

RUN npm i -g yarn

COPY ./features /app/features
COPY ./package.json /app/package.json
COPY ./yarn.lock /app/yarn.lock

WORKDIR /app

RUN yarn --frozen-lockfile && yarn cache clean

ENTRYPOINT ["yarn", "test:e2e"]
