version: "3"

services:
  db:
    build: ./db
    ports:
      - ${DB_PORT}:5432
    environment:
      # The JWT secret is used whithin the api.login() function:
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
     - postgre-data:/var/lib/postgresql/data

  # https://postgrest.org/en/stable/install.html#containerized-postgrest-and-db-with-docker-compose
  api:
    image: postgrest/postgrest
    ports:
      - ${API_PORT}:3000
    links:
      - db:db
    environment:
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_DB_SCHEMA: ${PGRST_DB_SCHEMA}
      PGRST_DB_URI: postgres://postgres@db:${DB_PORT}/cdtn
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
    depends_on:
      - db

  web:
    build: ./packages/contrib
    ports:
      - ${WEB_PORT}
    environment:
      API_PORT: ${API_PORT}
      WEB_PORT: ${WEB_PORT}

  master:
    build: .
    environment:
      PGRST_DB_URI: postgres://postgres@db:5432/cdtn
    links:
      - db:db
    depends_on:
      - db
    # https://github.com/docker/compose/issues/1926#issuecomment-135068628
    command: tail -f /dev/null

volumes:
  postgre-data:
