version: "3"

services:
  db:
    image: igabriele/postgresql-jwt
    ports:
      - ${DB_PORT}:5432
    environment:
      # The JWT secret is used whithin the api.login() function:
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgre-data:/var/lib/postgresql/data
      - ./backups:/backups

  # https://postgrest.org/en/stable/install.html#containerized-postgrest-and-db-with-docker-compose
  api:
    image: postgrest/postgrest:v6.0.2
    ports:
      - ${API_PORT}:3000
    environment:
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_DB_SCHEMA: ${PGRST_DB_SCHEMA}
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
    depends_on:
      - db

  web:
    build:
      context: ./packages/contrib
      args:
        API_DOCKER_URI: http://api:3000
        API_URI: ${API_URI}
        NODE_ENV: ${NODE_ENV}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    environment:
      DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      NODE_ENV: ${NODE_ENV}
      WEB_PORT: ${WEB_PORT}
    depends_on:
      - api

volumes:
  postgre-data:
