version: "3"

services:
  postgre:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cdtn

  # https://postgrest.org/en/stable/install.html#containerized-postgrest-and-db-with-docker-compose
  server:
    image: postgrest/postgrest
    ports:
      - 3200:3000
    links:
      - postgre:db
    environment:
      PGRST_DB_URI: postgres://postgres@db:5432/cdtn
      PGRST_DB_SCHEMA: api
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      # In production, this role should not be the same as the one used for the connection.
      PGRST_DB_ANON_ROLE: anonymous
    depends_on:
      - postgre
