version: "3"

services:
  postgre:
    build: ./db
    ports:
      - 5432:5432
    environment:
      # The JWT secret is used whithin the api.login() function:
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}

  # https://postgrest.org/en/stable/install.html#containerized-postgrest-and-db-with-docker-compose
  server:
    image: postgrest/postgrest
    ports:
      - 3200:3000
    links:
      - postgre:db
    environment:
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_DB_SCHEMA: ${PGRST_DB_SCHEMA}
      PGRST_DB_URI: postgres://postgres@db:5432/cdtn
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
    depends_on:
      - postgre
