version: "3"

services:
  db:
    image: igabriele/postgresql-jwt
    ports:
      - ${DB_PORT}:5432
    environment:
      # The JWT secret is used whithin the api.login() function:
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
     - postgre-data:/var/lib/postgresql/data
     - ./backups:/backups

  # https://postgrest.org/en/stable/install.html#containerized-postgrest-and-db-with-docker-compose
  api:
    image: postgrest/postgrest
    ports:
      - ${API_PORT}:3000
    environment:
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_DB_SCHEMA: ${PGRST_DB_SCHEMA}
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
    depends_on:
      - db

  web:
    build: ./packages/contrib
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    environment:
      API_URI: ${API_URI}
      WEB_PORT: ${WEB_PORT}
    depends_on:
      - api

  master:
    build: .
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}
    depends_on:
      - db
    # https://github.com/docker/compose/issues/1926#issuecomment-135068628
    command: tail -f /dev/null

  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    links:
      - docker-dind
    environment:
      DOCKER_HOST: tcp://docker-dind:2375
      WEB_URI: http://web:${WEB_PORT}
    depends_on:
      - web

  # This is required in order to enable docker-in-docker when running the "test" service:
  docker-dind:
    image: docker:dind
    privileged: true
    expose:
      - 2375

volumes:
  postgre-data:
