export default {
  // Multiple agreements:
  AGREEMENTS_LOAD: "AGREEMENTS_LOAD",
  AGREEMENTS_LOAD_FAILURE: "AGREEMENTS_LOAD_FAILURE",
  AGREEMENTS_LOAD_SUCCESS: "AGREEMENTS_LOAD_SUCCESS",

  // One answer:
  ANSWERS_CANCEL: "ANSWERS_CANCEL",
  ANSWERS_CANCEL_FAILURE: "ANSWERS_CANCEL_FAILURE",
  ANSWERS_LOAD: "ANSWERS_LOAD",

  // Multiple answers:
  ANSWERS_LOAD_FAILURE: "ANSWERS_LOAD_FAILURE",
  ANSWERS_LOAD_SUCCESS: "ANSWERS_LOAD_SUCCESS",
  ANSWERS_SET_FILTER: "ANSWERS_SET_FILTER",
  ANSWERS_SET_FILTERS: "ANSWERS_SET_FILTERS",
  ANSWERS_SET_FILTERS_FAILURE: "ANSWERS_SET_FILTERS_FAILURE",
  ANSWERS_SET_FILTERS_SUCCESS: "ANSWERS_SET_FILTERS_SUCCESS",
  ANSWERS_SET_FILTER_FAILURE: "ANSWERS_SET_FILTER_FAILURE",
  ANSWERS_SET_FILTER_SUCCESS: "ANSWERS_SET_FILTER_SUCCESS",
  ANSWERS_TOGGLE_CHECK: "ANSWERS_TOGGLE_CHECK",
  ANSWERS_TOGGLE_CHECK_FAILURE: "ANSWERS_TOGGLE_CHECK_FAILURE",
  ANSWERS_TOGGLE_CHECK_SUCESS: "ANSWERS_TOGGLE_CHECK_SUCESS",
  ANSWERS_UPDATE_GENERIC_REFERENCE: "ANSWERS_UPDATE_GENERIC_REFERENCE",
  ANSWERS_UPDATE_GENERIC_REFERENCE_FAILURE: "ANSWERS_UPDATE_GENERIC_REFERENCE_FAILURE",
  ANSWERS_UPDATE_IS_PUBLISHED_REFERENCE: "ANSWERS_UPDATE_IS_PUBLISHED_REFERENCE",
  ANSWERS_UPDATE_IS_PUBLISHED_REFERENCE_FAILURE: "ANSWERS_UPDATE_IS_PUBLISHED_REFERENCE_FAILURE",
  ANSWERS_UPDATE_STATE: "ANSWERS_UPDATE_STATE",
  ANSWERS_UPDATE_STATE_FAILURE: "ANSWERS_UPDATE_STATE_FAILURE",
  ANSWER_LOAD_ONE: "ANSWER_LOAD_ONE",
  ANSWER_LOAD_ONE_FAILURE: "ANSWER_LOAD_ONE_FAILURE",
  ANSWER_LOAD_ONE_SUCCESS: "ANSWER_LOAD_ONE_SUCCESS",

  // One comment:
  COMMENTS_DELETE: "COMMENT_REMOVE",
  COMMENTS_DELETE_FAILURE: "COMMENT_REMOVE_FAILURE",
  COMMENTS_LOAD: "COMMENT_LOAD",
  COMMENTS_LOAD_FAILURE: "COMMENT_LOAD_FAILURE",

  // Multiple comments:
  COMMENTS_LOAD_SUCCESS: "COMMENT_LOAD_SUCCESS",
  COMMENT_CREATE_ONE: "COMMENT_CREATE_ONE",
  COMMENT_CREATE_ONE_FAILURE: "COMMENT_CREATE_ONE_FAILURE",
  COMMENT_CREATE_ONE_SUCCESS: "COMMENT_CREATE_ONE_SUCCESS",
  COMMENT_TOGGLE_PRIVACY: "COMMENT_TOGGLE_PRIVACY",

  // Multiple questions:
  LOGS_LOAD: "LOGS_LOAD",
  LOGS_LOAD_FAILURE: "LOGS_LOAD_FAILURE",
  LOGS_LOAD_SUCCESS: "LOGS_LOAD_SUCCESS",

  // Multiple questions:
  MODAL_CLOSE: "MODAL_CLOSE",
  MODAL_OPEN: "MODAL_OPEN",
  MODAL_SUBMIT: "MODAL_SUBMIT",

  // Modal:
  QUESTIONS_LOAD: "QUESTIONS_LOAD",
  QUESTIONS_LOAD_FAILURE: "QUESTIONS_LOAD_FAILURE",
  QUESTIONS_LOAD_SUCCESS: "QUESTIONS_LOAD_SUCCESS"
};
