version: 2.1

jobs:
  unit-test:
    docker:
      - image: "cimg/node:lts"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --ignore-scripts
      - run:
          name: Lint Code
          command: yarn test:lint
      - run:
          name: Check Types
          command: yarn test:type
      - run:
          name: Run Unit Tests
          command: yarn test:unit --runInBand
          no_output_timeout: 1h
      - run:
          name: Update Code Coverage
          command: npx codecov
          when: on_success

workflows:
  version: 2
  test:
    jobs:
      - unit-test
