version: 2.1

orbs:
  node: circleci/node@4.2.0

jobs:
  unit-test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run:
          name: Print Node Version
          command: node --version
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --ignore-scripts
      - run:
          name: Run Unit Tests
          command: yarn test
          no_output_timeout: 30m
      - run:
          name: Update Code Coverage
          command: npx codecov
          when: on_success

workflows:
  version: 2
  test:
    jobs:
      - unit-test
