root: true

extends:
  - "@socialgouv/eslint-config-strict"
  - prettier

plugins:
  - sort-requires
  - prettier

env:
  browser: false
  node: true

rules:
  no-console: ["error", { allow: ["info", "error", "warn"] }]
  prettier/prettier: error
  sort-requires/sort-requires: error

overrides:
  - files:
      - "jest.setup.js"
      - "*.test.js"
    env:
      jest: true
