export default {
  // One answer:
  ANSWER_LOAD_ONE: "ANSWER_LOAD_ONE",
  ANSWER_LOAD_ONE_FAILURE: "ANSWER_LOAD_ONE_FAILURE",
  ANSWER_LOAD_ONE_SUCCESS: "ANSWER_LOAD_ONE_SUCCESS",

  // Multiple answers:
  ANSWERS_CANCEL: "ANSWERS_CANCEL",
  ANSWERS_CANCEL_FAILURE: "ANSWERS_CANCEL_FAILURE",
  ANSWERS_LOAD: "ANSWER_LOAD",
  ANSWERS_LOAD_FAILURE: "ANSWER_LOAD_FAILURE",
  ANSWERS_LOAD_SUCCESS: "ANSWER_LOAD_SUCCESS",
  ANSWER_UPDATE_GENERIC_REFERENCE: "ANSWER_UPDATE_GENERIC_REFERENCE",
  ANSWER_UPDATE_GENERIC_REFERENCE_FAILURE:
    "ANSWER_UPDATE_GENERIC_REFERENCE_FAILURE",
  ANSWER_UPDATE_IS_PUBLISHED_REFERENCE: "ANSWER_UPDATE_IS_PUBLISHED_REFERENCE",
  ANSWER_UPDATE_IS_PUBLISHED_REFERENCE_FAILURE:
    "ANSWER_UPDATE_IS_PUBLISHED_REFERENCE_FAILURE",
  ANSWER_UPDATE_STATE: "ANSWER_UPDATE_STATE",
  ANSWER_UPDATE_STATE_FAILURE: "ANSWER_UPDATE_STATE_FAILURE",
  ANSWERS_TOGGLE_CHECK: "ANSWERS_TOGGLE_CHECK",
  ANSWERS_TOGGLE_CHECK_FAILURE: "ANSWERS_TOGGLE_CHECK_FAILURE",
  ANSWERS_TOGGLE_CHECK_SUCESS: "ANSWERS_TOGGLE_CHECK_SUCESS",

  // One comment:
  COMMENT_ADD: "COMMENT_ADD",
  COMMENT_ADD_FAILURE: "COMMENT_ADD_FAILURE",
  COMMENT_ADD_SUCCESS: "COMMENT_ADD_SUCCESS",
  COMMENT_TOGGLE_PRIVACY: "COMMENT_TOGGLE_PRIVACY",

  // Multiple comments:
  COMMENTS_LOAD: "COMMENT_LOAD",
  COMMENTS_LOAD_FAILURE: "COMMENT_LOAD_FAILURE",
  COMMENTS_LOAD_SUCCESS: "COMMENT_LOAD_SUCCESS",
  COMMENTS_REMOVE: "COMMENT_REMOVE",
  COMMENTS_REMOVE_FAILURE: "COMMENT_REMOVE_FAILURE",

  // Modal:
  MODAL_CLOSE: "MODAL_CLOSE",
  MODAL_OPEN: "MODAL_OPEN",
  MODAL_SUBMIT: "MODAL_SUBMIT"
};
