export default {
  ANSWERS_CANCEL: "ANSWERS_CANCEL",
  ANSWERS_CANCEL_FAILURE: "ANSWERS_CANCEL_FAILURE",
  ANSWERS_CANCEL_SUCCESS: "ANSWERS_CANCEL_SUCCESS",
  ANSWERS_LOAD: "ANSWER_LOAD",
  ANSWERS_LOAD_FAILURE: "ANSWER_LOAD_FAILURE",
  ANSWERS_LOAD_SUCCESS: "ANSWER_LOAD_SUCCESS",
  ANSWERS_SET_GENERIC_REFERENCE: "ANSWERS_SET_GENERIC_REFERENCE",
  ANSWERS_SET_GENERIC_REFERENCE_FAILURE:
    "ANSWERS_SET_GENERIC_REFERENCE_FAILURE",
  ANSWERS_SET_GENERIC_REFERENCE_SUCCESS:
    "ANSWERS_SET_GENERIC_REFERENCE_SUCCESS",
  ANSWERS_SET_STATE: "ANSWERS_SET_STATE",
  ANSWERS_SET_STATE_FAILURE: "ANSWERS_SET_STATE_FAILURE",
  ANSWERS_SET_STATE_SUCCESS: "ANSWERS_SET_STATE_SUCCESS",
  MODAL_CLOSE: "MODAL_CLOSE",
  MODAL_OPEN: "MODAL_OPEN",
  MODAL_SUBMIT: "MODAL_SUBMIT"
};
