extends:
  - "@socialgouv/eslint-config-react"

rules:
  jsx-a11y/anchor-is-valid: off
  jsx-a11y/label-has-for: off
  react/prop-types: off
  no-console: [
    "error",
    allow: [
      "warn",
      "error"
    ]
  ]
