version: '2.0'

services:
  kinto:
    image: kinto/kinto-server:13.5.0
    restart: always
    environment:
      - KINTO_STORAGE_BACKEND=kinto.core.storage.postgresql
      - KINTO_STORAGE_URL=postgresql://postgres:postgres@db/postgres
      - KINTO_PERMISSION_BACKEND=kinto.core.permission.postgresql
      - KINTO_PERMISSION_URL=postgresql://postgres:postgres@db/postgres
      - KINTO_BUCKET_CREATE_PRINCIPALS=system.Everyone
  db:
    image: postgres:10.10
    restart: always
    environment:
      # master password
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

