extends:
  - "@socialgouv/eslint-config-react-strict"

rules:
  no-console: ["error", { allow: ["info", "error", "warn"] }]
  jest/no-disabled-tests: off
  react/prop-types: off

overrides:
  - files:
      - "jest.setup.js"
      - "*.test.js"

    env:
      jest: true

    globals:
      testRender: true
      waitFor: true
