extends:
  - "@socialgouv/eslint-config-react"

rules:
  max-len: ["error", { "code": 80 }]
  no-console: ["error", { allow: ["info", "error", "warn"] }]
  no-extra-boolean-cast: [0]

  jest/no-disabled-tests: off

  jsx-a11y/anchor-is-valid: off
  jsx-a11y/no-redundant-roles: off

  react/display-name: off
  react/prop-types: off

overrides:
  files:
    - "__mocks__/*"
    - "jest.setup.js"
    - "*.test.js"

  env:
    jest: true

  globals:
    waitFor: true
