extends:
  - "@socialgouv/eslint-config-react"

rules:
  max-len: ["error", { "code": 80 }]
  no-console: ["error", { allow: ["info", "error", "warn"] }]

  jsx-a11y/anchor-is-valid: off

  react/display-name: off
  react/prop-types: off

overrides:
  - files:
    - "*.test.js"

    env:
      jest: true
