name: Review

on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:
  register:
    name: Build & Register images
    runs-on: ubuntu-latest
    steps:
      - name: Register docker image for app
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: "cdtn"
          imageName: cdtn-backoffice/app
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "./Dockerfile"
          dockercontext: "./packages/app"
          dockerbuildargs: |
            CDTN_API_URL=https://cdtn-api.fabrique.social.gouv.fr
  manifests:
    name: Generate k8s manifests
    runs-on: ubuntu-latest
    steps:
      - name: Install
        shell: bash
        run: |
          yarn add @socialgouv/kosko-charts
      - name: Get k8s infos
        id: k8s
        shell: bash
        run: |
          RAW_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          BRANCH=$(npx @socialgouv/env-slug "${RAW_BRANCH}")
          echo "::set-output name=branch::$(echo ${BRANCH})"
      - name: Use k8s manifests generation
        uses: SocialGouv/actions/k8s-manifests@v1
        with:
          environment: "dev"
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [register, manifests]
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-deploy@v1
        with:
          environment: "dev"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}

